### PR TITLE
Finished TODOs

### PR DESCRIPTION
**Pull request by realsarm**

### CODE REVIEW

**Comment by alimahdiyar** [comment]
Commit messages are not clean

**Comment by alimahdiyar** [comment]
no exceptions in login
no getter for username needed for now. fixing TODO 2 error is easier than you think!

**Comment by s-arme** [comment]
There is a "Wrong Username or password" exception in login function in line 67

**Comment by alimahdiyar** [comment]
> There is a "Wrong Username or password" exception in login function in line 67 From: Ali Mahdiyar Sent: 28 October 2018 13:58 To: alimahdiyar/stackoverflow-in-cpp Cc: s-arme; Author Subject: Re: [alimahdiyar/stackoverflow-in-cpp] Finished TODOs (#3) no exceptions in login no getter for username needed for now. fixing TODO 2 error is easier than you think! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I saw exception now. But there are still problems with username.

**Comment by s-arme** [comment]
Do you mean easier solution instead of getter for username or …?!

**Comment by s-arme** [comment]
@alimahdiyar 
> Try fixing TODO 2 without even touching the for loop.
The problem is now **fixed** with old for loop style.

**Pull request merged**
